### PR TITLE
Complete redesign of Writeboard

### PR DESCRIPTION
**Pull request by w-henderson**
I've completely redesigned and rebranded Writeboard, making it easier to maintain and providing better mobile support.

### CODE REVIEW

**Review by flauntingspade4 — COMMENTED** [review]
Looks good, the SCSS looks to be improved well-would be better if written in rust tho 😐

**Comment by w-henderson** [comment]
> Looks good, the SCSS looks to be improved well-would be better if written in rust tho 😐

As much as I love Rust, I feel like it is not a great fit for this serverless project. If you want to rewrite the whole thing in Rust, however, feel free to fork!

**Comment by w-henderson** [comment]
**Bug**: visual glitch when using pen eraser but not when manually selecting eraser

**Comment by w-henderson** [comment]
**Bug**: you can send empty messages

**Comment by w-henderson** [comment]
**Bug**: text goes behind chat send button if the message is too long
**Location**: somewhere in `_chat.scss`

**Pull request merged**
